In [1]:
import numpy as np

In [ ]:
#   全部的变量的偏导数汇总而成的向量称为梯度


In [7]:
def numerical_gradient(f,x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x) # generate an array with the same shape as x 
    for idx in range(x.size):
        tmp_val = x[idx]
        
        # calculate f(x+h)
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        # calculate f(x-h)
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1-fxh2) / (2 * h)
        x[idx] = tmp_val 
        
    return grad 

In [8]:
def function_2(x):
    return x[0] ** 2 + x[1] ** 2

In [9]:
numerical_gradient(function_2,np.array([3.0,4.0]))

array([6., 8.])

In [11]:
numerical_gradient(function_2,np.array([0.0,2.0]))

array([0., 4.])

In [12]:
numerical_gradient(function_2,np.array([3.0,0.0]))

array([6., 0.])

In [ ]:
## 梯度指示的方向是各点处的函数值减少最多的方向。 


In [13]:
def gradient_descent(f,init_x,lr = 0.01,step_num = 100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f,x)
        x -= lr * grad
        
        
    return x

In [14]:
init_x = np.array([-3.0,4.0])

gradient_descent(function_2,init_x = init_x,lr = 0.1,step_num = 100)



array([-6.11110793e-10,  8.14814391e-10])

In [19]:
init_x = np.array([-3.0,4.0])
gradient_descent(function_2,init_x = init_x,lr = 10.0,step_num = 100)


array([-2.58983747e+13, -1.29524862e+12])

In [20]:
init_x = np.array([-3.0,4.0])
gradient_descent(function_2,init_x = init_x,lr = 1e-10,step_num = 100)

array([-2.99999994,  3.99999992])