In [1]:
import numpy as np

In [5]:
X = np.array([1,2])
X

array([1, 2])

In [8]:
X.shape

(2,)

In [6]:
W = np.array([[1,3,5],[2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [7]:
W.shape

(2, 3)

In [10]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]


W12, it means tht the weight of the connection from the 1st layer to the 2nd layer. 1 means the location of the 2nd layer. 
偏置权重的数量取决于后一层神经元的数量，比如我们设定了，后一层有3个神经元，那么它的偏置权重就有3个。 


In [20]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.2,0.3],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

In [21]:
print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)


In [22]:
A1 = np.dot(X,W1) + B1

In [23]:
print(A1)

[0.3 0.6 0.9]


In [24]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [25]:
Z1 = sigmoid(A1)
print(Z1)

[0.57444252 0.64565631 0.7109495 ]


In [27]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [28]:
A2 = np.dot(Z1,W2) + B2
Z2 = sigmoid(A2)

In [31]:
def identity_function(x):
    return x 

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2,W3) + B3
Y = identity_function(A3)

In [32]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.2,0.3],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network

def forward(network,x):
    W1,W2,W3 = network['W1'],network['W2'],network['W3']
    b1,b2,b3 = network['b1'],network['b2'],network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    
    a3 = np.dot(z2,W3) + b3
    z3 = sigmoid(a3)
    
    y = identity_function(a3)
    
    return y 


In [33]:
network = init_network()
x = np.array([1.0,0.5])
y = forward(network,x)
print(y)

[0.31520253 0.69264772]


### Softmax function

In [35]:
a = np.array([0.3,2.9,4.0])
a 

array([0.3, 2.9, 4. ])

In [37]:
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [38]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [40]:
y = exp_a/sum_exp_a 
y 

array([0.01821127, 0.24519181, 0.73659691])

In [45]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y 
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [46]:
a = np.array([[1010,1000,990]])

np.exp(a) / np.sum(np.exp(a))


/var/folders/x1/rg74ttxx7bb0_2z1wxpb2z940000gn/T/ipykernel_2808/3025627023.py:3: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
/var/folders/x1/rg74ttxx7bb0_2z1wxpb2z940000gn/T/ipykernel_2808/3025627023.py:3: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))


array([[nan, nan, nan]])

In [50]:
c = np.max(a)
a -c 

array([[  0, -10, -20]])

In [51]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([[9.99954600e-01, 4.53978686e-05, 2.06106005e-09]])

In [53]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a 
    return y 


In [54]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)

print(y)

[0.01821127 0.24519181 0.73659691]


In [55]:
np.sum(y)

1.0